#!/bin/bash
source_pic_path="/Users/maqing/Project/github/kubegems/kubegems.io/static"
mv ${source_pic_path}/img/docs/example-nginx-deploy.jpg  ./assets
mv ${source_pic_path}/img/docs/example-nginx-deploy-yaml.jpg  ./assets
mv ${source_pic_path}/img/docs/example-nginx-service.jpg  ./assets
mv ${source_pic_path}/img/docs/example-nginx-gateway.jpg  ./assets
mv ${source_pic_path}/img/docs/example-nginx-gateway-success.jpg  ./assets
mv ${source_pic_path}/img/docs/example-nginx-gateway-info.jpg  ./assets
mv ${source_pic_path}/img/docs/example-nginx-ingress.jpg  ./assets
mv ${source_pic_path}/img/docs/example-nginx-ingress.jpg  ./assets
mv ${source_pic_path}/img/docs/example-nginx-ingress-success.jpg  ./assets
mv ${source_pic_path}/img/docs/example-appstore-list.jpg  ./assets
mv ${source_pic_path}/img/docs/example-appstore-mysql.jpg  ./assets
mv ${source_pic_path}/img/docs/example-appstore-mysql-1.jpg  ./assets
mv ${source_pic_path}/img/docs/example-appstore-mysql-table.jpg  ./assets
mv ${source_pic_path}/img/docs/example-appstore-mysql-values.jpg  ./assets
mv ${source_pic_path}/img/docs/example-appstore-mysql-success.jpg  ./assets
mv ${source_pic_path}/img/docs/example-appstore-mysql-info.jpg  ./assets
mv ${source_pic_path}/img/docs/example-appstore-mysql-status.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-pod-info.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-pod-logs.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-pod-exec.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-workload-info.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-workload-replicas.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-workload-rollout.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-hpa.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-resource-recommend.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-resource-set.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-workload-resource.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-logging-dash.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-logging-labels.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-logging-filter-run.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-logging-time-picker.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-logging-history.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-pvc-extend.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-pvc-resize.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-pvc-snapshot.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-env-enter.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-env-rq.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-env-lr.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-cluster-quota.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-tenant-member.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-project-enter.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-project-member.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-env-enter.jpg  ./assets
mv ${source_pic_path}/img/docs/example-common-env-member.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-login.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-cluster.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-import-cluster.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-cluster-list.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-cluster-info.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-tenant-list.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-tenant-create.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-tenant-info.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-tenant-quota.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-dash.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-project.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-quota.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-info.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-workload.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-deploy-1.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-deploy-2.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-deploy-3.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-deploy-4.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-deploy-5.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-deploy-success.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-service-1.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-service-2.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-ingress-1.jpg  ./assets
mv ${source_pic_path}/img/docs/admin-first-demo-env-ingress-info.jpg  ./assets
